AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BUDAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: production
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MethodSettings:
      - ResourcePath: /v1/polls
        CachingEnabled: true
        CacheTtlInSeconds: 600
        HttpMethod: GET
      - ResourcePath: /v1/polls/{pollId}
        CachingEnabled: true
        CacheTtlInSeconds: 600
        HttpMethod: GET
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '1'
          title: kodo
        basePath: /v1
        schemes:
        - https
        paths:
          /v1/polls:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:349390452115:function:BUDGetPollsHandler/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
          /v1/polls/{pollId}:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:349390452115:function:BUDGetPollHandler/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                cacheNamespace: cs0i4n
                cacheKeyParameters:
                - method.request.path.pollId
  BUDGetPollHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BUDGetPollHandler
      Handler: src/handlers/polls/getPoll.handler
      Runtime: nodejs8.10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/polls/{pollId}
            Method: Get
            RestApiId:
              Ref: BUDAPI
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:GetItem
          Resource:
            Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/BUDPollTable
      CodeUri: s3://between-us-drivers-infrastructure/7a31daa53eec49edcae6bdb2c9fc869b
  BUDGetPollsHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BUDGetPollsHandler
      Handler: src/handlers/polls/getPolls.handler
      Runtime: nodejs8.10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /v1/polls
            Method: Get
            RestApiId:
              Ref: BUDAPI
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:Scan
          Resource:
            Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/BUDPollTable
      CodeUri: s3://between-us-drivers-infrastructure/7a31daa53eec49edcae6bdb2c9fc869b
  BUDPollTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BUDPollTable
      AttributeDefinitions:
      - AttributeName: pollId
        AttributeType: S
      KeySchema:
      - AttributeName: pollId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  BUDUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BUDUserTable
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  BUDUserVoteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BUDUserVoteTable
      AttributeDefinitions:
      - AttributeName: userVoteId
        AttributeType: S
      KeySchema:
      - AttributeName: userVoteId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  BUDCommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BUDCommentTable
      AttributeDefinitions:
      - AttributeName: commentId
        AttributeType: S
      KeySchema:
      - AttributeName: commentId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  BUDCommentVoteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BUDCommentVoteTable
      AttributeDefinitions:
      - AttributeName: commentVoteId
        AttributeType: S
      KeySchema:
      - AttributeName: commentVoteId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
